# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: ab584b3d46b061ed59a9c957f45a96439722861d9effbabd8b10d42fb84eb0aeb94fe1a3bf6441687f06dfbb9df631ce1287b12de763a73812f2a3daceebea45

test:
  secret_key_base: 8d48582184512e211c1678efe52e1a7dcd4823c7e7b7e603ffc8e7ea75bc268d3ab2bdc597a54585fef34d979c50b1cf696a9abcefc29cf22ff85cc76fd0c81a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
